### ISSUE TITLE
Sonos Favorites aren't loaded

### ISSUE THREAD

**Issue by landonr** [landonr/esphome-remote#13]
**Describe the bug**
Sonos favorites are empty because they rely on a home assistant template

**Expected behavior**
All the sonos favorites should be listed in the Sources menu

**Additional context**
I use this template to get favorites formatted for the device but it should load the existing sensor.sonos_favorites 
```
      - name: Sonos Favorites List
        state: 'OK'
        attributes:
          items: '{{ state_attr("sensor.sonos_favorites", "items").values() | list | join("~") }}'
```

**Comment by abroooo** [comment]
Oh nice, the workaround did the trick for me 👍 
I don't mind the extra sensor but you're right, it's an external dependency.

**Comment by landonr** [comment]
If we can get rid of the sensor, we should be able to load playlists from spotify too. Spotcast has this playlists sensors that returns the same as the default sonos sensor
```
playlists: 
- uri: spotify:playlist:37i9dQZF1EIdNK9vIbNBMb
  name: Morning Mix
- uri: spotify:playlist:4772bP5KCO80HXMQsr7aol
  name: S/S 22 🫶🏻
...
```
