### ISSUE TITLE
remote wont boot without media players configured

### ISSUE THREAD

**Issue by goxofy** [landonr/esphome-remote#16]
Is it possible to support this hardware?

LILYGO® TTGO T-Display Keyboard For LNURLPoS

https://m.tb.cn/h.UeTxbek?tk=sYnC2zqligT

thanks a lot!

**Comment by landonr** [comment]
Yes it would be very easy to set up. The code for the rotary is 5 buttons (up,down,left,right,select) and 2 rotary directions (left,right). This keypad has 12 buttons + so you can easily just call the existing functions from the keypad buttons

**Comment by goxofy** [comment]
Hi @landonr , i am not a programer, could you please tell me which src file should I change? thanks!

**Comment by landonr** [comment]
what do you want each button to do?

**Comment by landonr** [comment]
here's the functions you have to call for each button
```
5 - buttonPressSelect();
4- buttonPressLeft();
6 - buttonPressRight();
8 - buttonPressDown();
2 - buttonPressUp();

# - buttonPressNext();
* - buttonPressPrevious();
```
in order to actually set up that keypad this component might be helpful https://github.com/Syralist/esphomekeypad. You can include that and then call the appropriate function based on which number is pressed

**Comment by goxofy** [comment]
@landonr ok thanks, i'll try this

**Comment by landonr** [comment]
just noticed this component which is better supported should be more straightforward to set up https://github.com/ssieb/custom_components/tree/vbus/components/matrix_keypad

**Comment by goxofy** [comment]
OK，thanks!

**Comment by goxofy** [comment]
hi @landonr , I have a question about tdisplay with Scrollwheel, what the Scrollwheel's enca pin and encb pin connect to?

**Comment by landonr** [comment]
I have it set up on pin 12 and 13. that side has enough IO for all of the buttons and the encoder. here's the esphome setup
```
sensor:
## Rotary
  - platform: rotary_encoder
    filters:
    - throttle: 0.01s
    name: "Rotary Encoder"
    internal: true
    pin_a:
      number: 12
      mode:
        input: true
        pullup: true
    pin_b:
      number: 13
      mode:
        input: true
        pullup: true
    id: rotary
    on_clockwise:
      - lambda: |-
          buttonPressWakeUpDisplay();
          buttonPressNext();
    on_anticlockwise:
      - lambda: |-
          buttonPressWakeUpDisplay();
          buttonPressPrevious();
```

**Comment by goxofy** [comment]
hi @landonr 

I made this remote with scrollwheel but when I power on the tdisplay, it only shows a logo, it doesn't work when i press any key.

the logs here, please help me

![Screenshot_2022-11-02-00-26-52-83_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/1695416/199287367-ac42baa3-f8ea-4f0b-9f5f-7af08348728b.jpg)

**Comment by landonr** [comment]
> hi @landonr 
> 
> I made this remote with scrollwheel but when I power on the tdisplay, it only shows a logo, it doesn't work when i press any key.
> 
> the logs here, please help me
> 
> ![Screenshot_2022-11-02-00-26-52-83_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/1695416/199287367-ac42baa3-f8ea-4f0b-9f5f-7af08348728b.jpg)
> 
>  

Have you set up the device in home assistant?

**Comment by goxofy** [comment]
yes， I set up it in home assistant

![Screenshot_2022-11-02-07-50-12-38_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/1695416/199363150-b3d855bf-aa0f-41fb-a81a-4de10e4b2a7c.jpg)

**Comment by landonr** [comment]
have you configured the media players in the `sharedRemoteConfig.yaml` to match your setup? It will show the boot screen until it finds a media player so the UI doesn't have empty states

**Comment by goxofy** [comment]
Hi @landonr , thanks for your reply!

I dont have a media player, I just want to control my lights and scene and scripts in home assistant ,so I deleted some code in the `sharedRemoteConfig.yaml`, here is my yaml , is it right?

```
logger:
  level: INFO

api:
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          goToScreenFromString(screen_name);

ota:

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true

  ap:
    ssid: "${friendly_name} Fallback"
    password: ${wifi_fallback_password}

captive_portal:

http_request:
  useragent: esphome/device
  timeout: 10s

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 75%
    blue: 10%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: color_accent_primary
    red: ${color_accent_primary_red}
    green: ${color_accent_primary_green}
    blue: ${color_accent_primary_blue}
  - id: my_gray_dark
    red: 40%
    green: 40%
    blue: 40%
  - id: my_gray_dark_2
    red: 8%
    green: 8%
    blue: 8%
  - id: my_gray
    red: 10%
    green: 10%
    blue: 10%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%

font:
## Font needs to be monospace!
  - file: "fonts/iosevka.ttf"
    id: large_font
    size: ${large_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: "fonts/iosevka.ttf"
    id: medium_font
    size: ${medium_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: "fonts/iosevka.ttf"
    id: small_font
    size: ${small_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_large
    size: ${icon_size_large}
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
    ]  
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_small
    size: ${icon_size}
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
    ]
    
globals:
## Size of the large font above
  - id: large_font_size
    type: int
    restore_value: no
    initial_value: ${large_font_size}
    
## Size of the medium font above
  - id: medium_font_size
    type: int
    restore_value: no
    initial_value: ${medium_font_size}
    
## Size of the small font above
  - id: small_font_size
    type: int
    restore_value: no
    initial_value: ${small_font_size}
    
## Height / width ratio of the monospace font used
  - id: font_size_width_ratio
    type: double
    restore_value: no
    initial_value: "0.6"
    
## Status bar height
  - id: header_height
    type: int
    restore_value: no
    initial_value: ${header_height}
    
## Global margin size
  - id: margin_size
    type: int
    restore_value: no
    initial_value: ${margin_size}
    
## Scrollbar total width
  - id: scroll_bar_width
    type: int
    restore_value: no
    initial_value: ${scroll_bar_width}
    
## Volume bar and media duration bar margin
  - id: bottom_bar_margin
    type: int
    restore_value: no
    initial_value: ${bottom_bar_margin}
    
## Height and width of the icons used in px
  - id: icon_size
    type: int
    restore_value: no
    initial_value: ${icon_size}
    
## Height and width of the icons used in px
  - id: icon_size_large
    type: int
    restore_value: no
    initial_value: ${icon_size_large}
    
## Max lines on now playing screen before truncating happens
  - id: now_playing_max_lines
    type: int
    restore_value: no
    initial_value: ${now_playing_max_lines}
    
## Draw buttons in now playing menu for 3 button devices
  - id: draw_now_playing_menu
    type: bool
    restore_value: no
    initial_value: ${draw_now_playing_menu}
    
## Draw battery icon if battery level is supported
  - id: draw_battery_level
    type: bool
    restore_value: no
    initial_value: ${draw_battery_level}
    
## Draw volume level in header
  - id: draw_volume_level
    type: bool
    restore_value: no
    initial_value: ${draw_volume_level}
    
## Draw shuffle icon if shuffle is disabled
  - id: draw_shuffle_disabled
    type: bool
    restore_value: no
    initial_value: ${draw_shuffle_disabled}
    
## Draw time in header
  - id: draw_header_time
    type: bool
    restore_value: no
    initial_value: ${draw_header_time}
    
## Customize device boot name
  - id: boot_device_name
    type: std::string
    restore_value: no
    initial_value: ${boot_name}

## Turn off display after x seconds of idle
  - id: display_timeout
    type: int
    restore_value: no
    initial_value: ${display_timeout}

## Go to sleep after x seconds of idle
  - id: sleep_after
    type: int
    restore_value: no
    initial_value: ${sleep_after}

## Let the menu selection roll-over when reaching the beginning/end
  - id: menu_rollover_on
    type: bool
    restore_value: no
    initial_value: ${menu_rollover_on}

## Find a new active media player if the current active one stops playing
  - id: sync_active_player
    type: bool
    restore_value: no
    initial_value: ${sync_active_player}

## Black background
  - id: dark_mode
    type: bool
    restore_value: no
    initial_value: ${dark_mode}
      
interval:
  - interval: 1s
    then:
    - lambda: |-
        idleTick();
  - interval: 0.3s
    then:
    - lambda: |-
        activeTick();

deep_sleep:
  id: deep_sleep_1

binary_sensor:
  - platform: status
    name: "${boot_name} Node Status"
    id: system_status

time:
  - platform: homeassistant
    id: esptime

custom_component:
# Home assistant speakers and tv. Set TV up with a sound bar

 
 ## Home assistant scripts and scenes. Set with a friendly name
 - lambda: |-
     std::vector<BaseService> scenes { 
       ScriptService("script.evevator_call", "evevator"), 
     };
     sceneGroup->setup(scenes);
     App.register_component(sceneGroup);
     return {sceneGroup};
   id: scene_group_component

 ## Home assistant lights. Set with a friendly name
 - lambda: |-
     std::vector<FriendlyNameEntity> lights { 
       FriendlyNameEntity("light.yeelink_lamp2_ddab_light", "yeelink"), 
     };
     lightGroup->setup(lights);
     App.register_component(lightGroup);
     return {lightGroup};
   id: light_group_component

 ## Home assistant sensors. Set with a friendly name
 - lambda: |-
     std::vector<FriendlyNameEntity> sensors {
       FriendlyNameEntity("sensor.zm1_b0f893254433_temperature", "Ketingwendu"),
     };
     sensorGroup->setup(sensors);
     App.register_component(sensorGroup);
     return {sensorGroup};
   id: sensor_group_component

```

**Comment by landonr** [comment]
I'll have to make a fix where it doesn't care about media players! for now you can add `playerSearchFinished = true;` to the top of `void findActivePlayer(bool background = false) {` in esphomeRemotePlayer.h

**Comment by goxofy** [comment]
@landonr Thank you very much!!!! 

I will try it and waiting for your patch!

**Comment by goxofy** [comment]
Hi @landonr ,I have tried to add `playerSearchFinished = true;` but it also doesn't work,here is log


![image](https://user-images.githubusercontent.com/1695416/199715241-a7342872-4f1a-45e7-be57-ef00f91fac01.png)



and here is the code

![image](https://user-images.githubusercontent.com/1695416/199715404-ad48023e-8409-4af8-8047-2768ca98656f.png)


It seems like when I add `playerSearchFinished = true;`, the devices doesn't connect to the HA API because when I click the "Sleep Toggle" it shows 
![image](https://user-images.githubusercontent.com/1695416/199715804-8c99d3a3-15b6-4c1c-a053-8cf6031abeca.png)

**Comment by landonr** [comment]
can you share your full config? it seems like its getting disconnected from the api repeatedly. It might be trying to read something that doesn't exist. this thread might help https://github.com/esphome/issues/issues/3108#issuecomment-1216338545 also try increasing your log level to very_verbose and see what it says https://github.com/esphome/issues/issues/3108#issuecomment-1059764294

**Comment by goxofy** [comment]
Hi @landonr , 

This is `tdisplayremote.yaml` and I didn't change anything.
```
esphome:
  name: displayremote
  platform: ESP32
  board: featheresp32
  includes:
    - esphomeRemote/MenuGlobals.h
    - esphomeRemote/MenuTitle.h
    - esphomeRemote/FriendlyNameEntity.h
    - esphomeRemote/TextHelpers.h
    - esphomeRemote/esphomeRemotePlayer.h
    - esphomeRemote/esphomeRemoteService.h
    - esphomeRemote/esphomeRemoteLight.h
    - esphomeRemote/esphomeRemoteSensor.h
    - esphomeRemote/DisplayUpdateInterface.h
    - esphomeRemote/esphomeRemote.h
    - esphomeRemote/esphomeRemoteRotary.h

substitutions:
  boot_name: '"TDisplay Remote <3"'
  friendly_name: "TDisplay Remote"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fallback_password: !secret wifi_password
  large_font_size: "24"
  medium_font_size: "15"
  small_font_size: "14"
  icon_size: "18"
  icon_size_large: "19"
  header_height: "16"
  margin_size: "4"
  scroll_bar_width: "6"
  bottom_bar_margin: "1"
  now_playing_max_lines: "5"
  draw_now_playing_menu: "false"
  draw_battery_level: "true"
  draw_volume_level: "false"
  draw_shuffle_disabled: "false"
  draw_header_time: "true"
  color_accent_primary_red: 0%
  color_accent_primary_green: 45%
  color_accent_primary_blue: 68%
  display_timeout: "16"
  sleep_after: "7200"
  menu_rollover_on: "false"
  sync_active_player: "true"
  dark_mode: "true"

<<: !include esphomeRemote/sharedRemoteConfig.yaml
  
sensor:
## Rotary
  - platform: rotary_encoder
    filters:
    - throttle: 0.01s
    name: "Rotary Encoder"
    internal: true
    pin_a:
      number: 12
      mode:
        input: true
        pullup: true
    pin_b:
      number: 13
      mode:
        input: true
        pullup: true
    id: rotary
    on_clockwise:
      - lambda: |-
          buttonPressWakeUpDisplay();
          buttonPressNext();
    on_anticlockwise:
      - lambda: |-
          buttonPressWakeUpDisplay();
          buttonPressPrevious();

## Needed to debounce screen updates for rotary. 17ms is close to 60fps for st7789v
  - platform: template
    id: display_update_tick
    filters:
      - debounce: 17ms
    on_value :
      then:
        - lambda: |-
            displayUpdateDebounced();
          
## Battery
  - platform: adc
    pin: 34
    attenuation: 11db
    name: "vccadc"
    update_interval: 250ms
    id: vcc_adc
    internal: true
    on_value:
      then:
        lambda: |-
          if (id(vcc_adc).state > 2.23) {
            if (charging == false) {
              charging = true;
            }
          } else {
            if (charging == true) {
              charging = false;
            }
          }
          id(vcc_adc_avg).publish_state(id(vcc_adc).state);
  - platform: template
    id: vcc_adc_avg
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 4
    on_value :
      then:
        - sensor.template.publish:
            id: batteryVoltage
            state: !lambda 'return id(vcc_adc).state;'
  - platform: template
    name: batteryVoltage
    id: batteryVoltage
    internal: true
    unit_of_measurement: 'V'
    on_value :
      then:
        - sensor.template.publish:
            id: batteryPercent
            state: !lambda 'return (id(batteryVoltage).state * 118) - 162;'
  - platform: template
    name: Battery Percent
    id: batteryPercent
    unit_of_measurement: '%'
    on_value_range:
      below: 5
      then:
        lambda: |-
          ESP_LOGE("SLEEP", "Low Power Supply %.3fV! Sleeping to protect battery", id(batteryPercent).state);
          id(sleep_toggle).turn_on();

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
    internal: true
    on_press:
      then:
      - lambda: |-
          buttonPressScreenLeft();
    on_release:
      then:
      - lambda: |-
          buttonReleaseScreenLeft();
    
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1
    internal: true
    on_press:
      then:
      - lambda: |-
          buttonPressScreenRight();
          
## Rotary buttons
  - platform: gpio
    internal: true
    pin:
      number: 21
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw5
    on_press:
      then:
      - lambda: |-
          buttonPressLeft();
  - platform: gpio
    internal: true
    pin:
      number: 22
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw4
    on_press:
      then:
      - lambda: |-
          buttonPressUp();
  - platform: gpio
    internal: true
    pin:
      number: 17
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw3
    on_press:
      then:
      - lambda: |-
          buttonPressRight();
  - platform: gpio
    internal: true
    pin:
      number: 2
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw2
    on_press:
      then:
      - lambda: |-
          buttonPressDown();
  - platform: gpio
    internal: true
    pin:
      number: 15
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw1
    on_press:
      then:
      - lambda: |-
          buttonPressSelect();

switch:
  - platform: template
    name: Sleep Toggle
    id: sleep_toggle
    optimistic: true
    on_turn_on:
      then:
        - deep_sleep.enter:
            id: deep_sleep_1
  - platform: gpio
    pin:
      number: 27
      inverted: false
    id: comb
    internal: true
  - platform: gpio
    pin:
      number: 26
      inverted: false
    id: coma
    internal: true
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight
    internal: true
    restore_mode: RESTORE_DEFAULT_ON

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 60s
    lambda: |-
      if (idleTime < 0) {
        ESP_LOGD("drawing menu", "turning on");
        id(backlight).turn_on();
        idleTime = 0;
      }

      drawMenu();
      return;
```


And this is `shareRemoteConfig.yaml`

```
logger:
  level: INFO

api:
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          goToScreenFromString(screen_name);

ota:


wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true

  ap:
    ssid: "${friendly_name} Fallback"
    password: ${wifi_fallback_password}

captive_portal:

http_request:
  useragent: esphome/device
  timeout: 10s

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 75%
    blue: 10%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: color_accent_primary
    red: ${color_accent_primary_red}
    green: ${color_accent_primary_green}
    blue: ${color_accent_primary_blue}
  - id: my_gray_dark
    red: 40%
    green: 40%
    blue: 40%
  - id: my_gray_dark_2
    red: 8%
    green: 8%
    blue: 8%
  - id: my_gray
    red: 10%
    green: 10%
    blue: 10%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%

font:
## Font needs to be monospace!
  - file: "fonts/iosevka.ttf"
    id: large_font
    size: ${large_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: "fonts/iosevka.ttf"
    id: medium_font
    size: ${medium_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: "fonts/iosevka.ttf"
    id: small_font
    size: ${small_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_large
    size: ${icon_size_large}
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
    ]  
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_small
    size: ${icon_size}
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
    ]
    
globals:
## Size of the large font above
  - id: large_font_size
    type: int
    restore_value: no
    initial_value: ${large_font_size}
    
## Size of the medium font above
  - id: medium_font_size
    type: int
    restore_value: no
    initial_value: ${medium_font_size}
    
## Size of the small font above
  - id: small_font_size
    type: int
    restore_value: no
    initial_value: ${small_font_size}
    
## Height / width ratio of the monospace font used
  - id: font_size_width_ratio
    type: double
    restore_value: no
    initial_value: "0.6"
    
## Status bar height
  - id: header_height
    type: int
    restore_value: no
    initial_value: ${header_height}
    
## Global margin size
  - id: margin_size
    type: int
    restore_value: no
    initial_value: ${margin_size}
    
## Scrollbar total width
  - id: scroll_bar_width
    type: int
    restore_value: no
    initial_value: ${scroll_bar_width}
    
## Volume bar and media duration bar margin
  - id: bottom_bar_margin
    type: int
    restore_value: no
    initial_value: ${bottom_bar_margin}
    
## Height and width of the icons used in px
  - id: icon_size
    type: int
    restore_value: no
    initial_value: ${icon_size}
    
## Height and width of the icons used in px
  - id: icon_size_large
    type: int
    restore_value: no
    initial_value: ${icon_size_large}
    
## Max lines on now playing screen before truncating happens
  - id: now_playing_max_lines
    type: int
    restore_value: no
    initial_value: ${now_playing_max_lines}
    
## Draw buttons in now playing menu for 3 button devices
  - id: draw_now_playing_menu
    type: bool
    restore_value: no
    initial_value: ${draw_now_playing_menu}
    
## Draw battery icon if battery level is supported
  - id: draw_battery_level
    type: bool
    restore_value: no
    initial_value: ${draw_battery_level}
    
## Draw volume level in header
  - id: draw_volume_level
    type: bool
    restore_value: no
    initial_value: ${draw_volume_level}
    
## Draw shuffle icon if shuffle is disabled
  - id: draw_shuffle_disabled
    type: bool
    restore_value: no
    initial_value: ${draw_shuffle_disabled}
    
## Draw time in header
  - id: draw_header_time
    type: bool
    restore_value: no
    initial_value: ${draw_header_time}
    
## Customize device boot name
  - id: boot_device_name
    type: std::string
    restore_value: no
    initial_value: ${boot_name}

## Turn off display after x seconds of idle
  - id: display_timeout
    type: int
    restore_value: no
    initial_value: ${display_timeout}

## Go to sleep after x seconds of idle
  - id: sleep_after
    type: int
    restore_value: no
    initial_value: ${sleep_after}

## Let the menu selection roll-over when reaching the beginning/end
  - id: menu_rollover_on
    type: bool
    restore_value: no
    initial_value: ${menu_rollover_on}

## Find a new active media player if the current active one stops playing
  - id: sync_active_player
    type: bool
    restore_value: no
    initial_value: ${sync_active_player}

## Black background
  - id: dark_mode
    type: bool
    restore_value: no
    initial_value: ${dark_mode}
      
interval:
  - interval: 1s
    then:
    - lambda: |-
        idleTick();
  - interval: 0.3s
    then:
    - lambda: |-
        activeTick();

deep_sleep:
  id: deep_sleep_1

binary_sensor:
  - platform: status
    name: "${boot_name} Node Status"
    id: system_status

time:
  - platform: homeassistant
    id: esptime

custom_component:
# Home assistant speakers and tv. Set TV up with a sound bar

 
 ## Home assistant scripts and scenes. Set with a friendly name
 - lambda: |-
     std::vector<BaseService> scenes { 
       ScriptService("script.evevator_call", "evevator"), 
     };
     sceneGroup->setup(scenes);
     App.register_component(sceneGroup);
     return {sceneGroup};
   id: scene_group_component

 ## Home assistant lights. Set with a friendly name
 - lambda: |-
     std::vector<FriendlyNameEntity> lights { 
       FriendlyNameEntity("light.yeelink_lamp2_ddab_light", "yeelink"), 
     };
     lightGroup->setup(lights);
     App.register_component(lightGroup);
     return {lightGroup};
   id: light_group_component

 ## Home assistant sensors. Set with a friendly name
 - lambda: |-
     std::vector<FriendlyNameEntity> sensors {
       FriendlyNameEntity("sensor.zm1_b0f893254433_temperature", "Ketingwendu"),
     };
     sensorGroup->setup(sensors);
     App.register_component(sensorGroup);
     return {sensorGroup};
   id: sensor_group_component
```
